### ISSUE TITLE
Method to extract valid through date from csig

### ISSUE THREAD

**Issue by drumm** [drupal/php-signify#13]
For https://www.drupal.org/project/drupalorg/issues/3061248, I'd like to keep track of the expiration date of generated csigs, so those artifacts can be purged and regenerated before they expire.

Since the signing oracle will be separate from what calls it, and the caller is already invoking `Verifier::verifyCsigMessage()` to validate the signing, I think it makes sense to have a `Verifier` method able to return the date.

Could `Verifier::verifyCsigMessage()` return an array of `['message' => …, 'valid_through_dt' => …]` or does another method make sense?

**Comment by davidstrauss** [comment]
I'm generally +1 on data extraction being part of validation APIs.
