### ISSUE TITLE
Construction of verifier should not accept date

### ISSUE THREAD

**Issue by heddn** [drupal/php-signify#15]
If the date is needed, it should be passed into any method that needs it.

Currently:
```php
$verifier = new Verifier($key, '2020-01-01');
$message = file_get_contents('contents-sha512sums.csig');
$file_list = $this->verifier->verifyCsigMessage($message);
$checksum_list = new ChecksumList($file_list, TRUE);
```
Future:
```php
$verifier = new Verifier($key);
$message = file_get_contents('contents-sha512sums.csig');
$file_list = $this->verifier->verifyCsigMessage($message, '2020-01-01');
$checksum_list = new ChecksumList($file_list, TRUE);
```

And more clearly (type hint added for clarity, we can't actually type hint and retain legacy PHP support):

```php
public function verifyCsigMessage(\string $message, \string? $date = null): \string
```

**Comment by davidstrauss** [comment]
I'm +1 to this change, but should we expect a more native PHP format for the date? Also, should we allow a default `null` date for "now" that causes the method to pull the current date itself?

**Comment by pwolanin** [comment]
I'm confused the change you are suggesting here.  The only reason we allow you to pass a date into the constructor is for testing a date that's not now.

I don't think this is a good change at first look

**Comment by pwolanin** [comment]
From slack discussion - we could change it so the constructor does not have the second arg, the optional date arg moves to the method but defaults to calling gmdate() when the date arg is null (the normal behavior)

This should only impact test code, reduces object state.

**Comment by davidstrauss** [comment]
I think this was what I had in mind:

``public function verifyCsigMessage(\string $message, \DateTime $now = null): \string``

Would that work? What are the upsides/downsides to using a string versus a DateTime and `null` versus the string "now"?

**Comment by heddn** [comment]
Just a note for posterity. `\DateTimeImmutable` was introduced in PHP 5.5. Not PHP 5.3.
